services:
  ui:
    build:
      context: .
      args:
        USE_LOCAL_EMBEDDINGS: "false"
        USE_CUDA: "false"
        USE_OLLAMA: "false"
        USE_SLIM: "false"
        USE_DOCLING: "true"
        USE_PLAYWRIGHT: "false"
    image: open-webui:latest
    container_name: llmui
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - ./openwebui:/app/backend/data
      - ./docs:/data/docs
    logging:
      options:
        max-size: "50m"
    env_file:
      - .env
    environment:
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_POOL_SIZE=${DATABASE_POOL_SIZE:-50}
      - DATABASE_POOL_MAX_OVERFLOW=${DATABASE_POOL_MAX_OVERFLOW:-5}
      - VECTOR_DB=${VECTOR_DB:-qdrant}
      - QDRANT_URI=${QDRANT_URI}
      - RAG_TOP_K=${RAG_TOP_K:-10}
      - ENABLE_RAG_HYBRID_SEARCH=${ENABLE_RAG_HYBRID_SEARCH:-true}
      - RAG_EMBEDDING_ENGINE=${RAG_EMBEDDING_ENGINE:-gemini}
      - RAG_EMBEDDING_MODEL=${RAG_EMBEDDING_MODEL:-models/gemini-embedding-001}
      - RAG_EMBEDDING_OPENAI_BATCH_SIZE=${RAG_EMBEDDING_OPENAI_BATCH_SIZE:-5}
      - RAG_EMBEDDING_BATCH_SIZE=${RAG_EMBEDDING_BATCH_SIZE:-16}
      - CHUNK_SIZE=${CHUNK_SIZE:-10000}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-200}
      - TOKENIZERS_PARALLELISM=${TOKENIZERS_PARALLELISM:-true}
      # Static app config
      - ENABLE_ADMIN_CHAT_ACCESS=false
      - ENABLE_OAUTH_SIGNUP=true
      - ENABLE_OLLAMA_API=true
      - WEBUI_NAME=HK WebUI
      - DEFAULT_USER_ROLE=user
      - ENABLE_MODEL_FILTER=true
      - ENABLE_COMMUNITY_SHARING=false
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - UVICORN_WORKERS=${UVICORN_WORKERS}
      - REDIS_URL=${REDIS_URL}

volumes:
  open-webui: {}
