"""add embed to knowledge

Revision ID: d2552259f02d
Revises: 922e7a387820
Create Date: 2024-11-22 16:38:25.247874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd2552259f02d'
down_revision: Union[str, None] = '922e7a387820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'embed' column to 'knowledge' table
    op.add_column(
        "knowledge",
        sa.Column("embed", sa.Boolean(), nullable=True, default=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge", "embed")
    # ### end Alembic commands ###
